name: Deploy Terraform Provider

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    env:
      GO111MODULE: on
      ORY_WORKSPACE_API_KEY: ${{ secrets.ORY_WORKSPACE_API_KEY }}
      ORY_PROJECT_ID: ${{ secrets.ORY_PROJECT_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Go Unit Tests
        run: go test -short -v ./...

  trigger-acceptance-tests:
    if: github.actor != 'dependabot[bot]'
    name: Trigger Acceptance Tests
    needs: unit-tests
    uses: ./.github/workflows/_terraform-tests.yml
    secrets: inherit
